import React from 'react';

export const metadata = {
    title: 'The AddPodduct in Next',
    description: 'Generated by create next app',
  }

const AddProduct = () => {
    return (
        <div>
            This is a testing nested route page for Dashboard. 
        </div>
    );
};

export default AddProduct;