import React from 'react';

export const metadata = {
    title: 'The Next About',
    description: 'Generated by create next app',
  }

const About = () => {
    return (
        <div>
            This the Next About page.
        </div>
    );
};

export default About;