import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Next Sadkatat',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={inter.className}>
        <nav className='flex justify-around bg-red-500'>
          <a className='text-xl bg-red-600 rounded-lg p-1'>Home</a>
          <a className='text-xl bg-red-600 rounded-lg p-1'>House</a>
          <a className='text-xl bg-red-600 rounded-lg p-1'>Hut</a>
        </nav>
        {children}
        <footer className='bg-red-500 text-center text-xl font-bold uppercase'>footer</footer>
      </body>
    </html>
  )
}


export default RootLayout;