import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Next Sadkatat',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={inter.className}>
          <nav>
            <a>home</a>
          </nav>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  )
}


export default RootLayout;