import Image from 'next/image'

export const metadata = {
  title: 'The Next Home',
  description: 'Generated by create next app',
}

const HomePage = () => {
  return (
    <main>
      <div>
        <h2>Main Body</h2>
      </div>
    </main>
  )
}

export default HomePage;