import React from 'react';

export const metadata = {
    title: 'The Next ManageProduct',
    description: 'Generated by create next app',
  }

const ManageProduct = () => {
    return (
        <div>
            The nested route for Dashboard .
            Note: This is the secound nested route.
        </div>
    );
};

export default ManageProduct;