import React from 'react';

export const metadata = {
    title: 'The Next Dashboard',
    description: 'Generated by create next app',
  }

const DashboardLayout = ({ children }) => {
    return (
        <div>
            Menu Drawer
            {children}
        </div>
    );
};

export default DashboardLayout;