import React from 'react';
export const metadata = {
    title: 'The Next Dashboard',
    description: 'Generated by create next app',
  }

const Dashboard = () => {
    return (
        <div>
            Dashboard for the testing of nestade route. 
        </div>
    );
};

export default Dashboard;